- hosts: all
  tasks:
  - name: Get contents of /etc/issue
    shell: cat /etc/issue
    register: is_ubuntu

  - name: Check if /etc/issue starts with Ubuntu
    when: is_ubuntu.stdout.find('Ubuntu') != -1
    debug: msg="This is Ubuntu!"
