  hosts: all
  tasks:
  - name: Check if /etc/issue starts with Ubuntu
    lineinfile:
      path: /etc/issue
      line: "Ubuntu"
      state: present
    check_mode: yes
    register: is_ubuntu
    failed_when: (is_ubuntu | changed) or (is_ubuntu | failed)
  - debug: msg="{{is_ubuntu.stdout_lines}}"
